# Generated by Django 5.1.1 on 2024-11-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_coupon_websitevisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heading',
            name='previous_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_headings', to='accounts.heading'),
        ),
    ]
