# Generated by Django 5.1.1 on 2024-09-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('short_link', models.URLField(max_length=500)),
                ('original_link', models.URLField(max_length=500)),
            ],
        ),
    ]
