# Generated by Django 5.1.1 on 2024-11-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_heading_is_end_heading_previous_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
