# Generated by Django 5.1.1 on 2024-09-09 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobalert',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='job_alerts/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passout_year',
            field=models.IntegerField(default=2023),
        ),
    ]
