# Generated by Django 5.1.1 on 2024-11-02 15:50

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_heading_is_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublesson',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Course Description'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Course Content')),
                ('order', models.PositiveIntegerField(editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='accounts.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progress',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.chapter'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('enrollment', 'chapter')},
        ),
        migrations.DeleteModel(
            name='Heading',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='content',
        ),
        migrations.DeleteModel(
            name='SubLesson',
        ),
    ]
