# Generated by Django 5.1.1 on 2024-11-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_sublesson_heading_remove_course_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
