# Generated by Django 5.1.1 on 2024-09-09 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobalert_author_jobalert_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
