# Generated by Django 5.1.1 on 2024-11-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_chapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
