# Generated by Django 5.1.1 on 2024-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='coupon',
            name='gives_free_premium',
            field=models.BooleanField(default=False),
        ),
    ]
