# Generated by Django 5.1.1 on 2024-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_coupon_discount_percentage_coupon_gives_free_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
