# Generated by Django 5.1.1 on 2024-09-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_coupon_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
