# Generated by Django 5.1.1 on 2024-09-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_jobalert_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobalert',
            name='image',
            field=models.ImageField(upload_to='job_alerts/'),
        ),
    ]
